apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: worker-deployment
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: worker-app
          # https://hub.docker.com/r/dockersamples/examplevotingapp_worker
          image: dockersamples/examplevotingapp_worker
            # no ports since worker is not a web app
          #ports:
          #- containerPort: 80